### PR TITLE
Add: mysql reserved words

### PR DESCRIPTION
**Pull request by eleijonmarck**

### CODE REVIEW

**Comment by inkel** [comment]
@eleijonmarck I've made some amends to the AWK script and now it's in a `escape.awk` file so it's easier to read and maintain. Let me know if that looks ok! I've tested it a few times and it seems to be giving the right output.

**Comment by eleijonmarck** [comment]
need to be tested with  - https://github.com/grafana/support-escalations/issues/4093#issuecomment-1275835298

**Comment by inkel** [comment]
@eleijonmarck let me know how the testing goes!

**Comment by DanCech** [comment]
we can likely simplify this a fair bit by just quoting every field name rather than trying to pick out reserved words.

**Comment by eleijonmarck** [comment]
@inkel thx inkel. talking to @DanCech on how we much we should put in the effort.

if he's suggestion seems easier to do, that would be great, I will also nuke the go code for reserved words

more suggestions he had:
- (optional) add backtick for tables that might be reserverd words

**Comment by inkel** [comment]
Adding backticks to all of the column names is much, much easier, I'm going to do that.

In addition, we could do the same for table names, and just backtick all of them, what do you think?

**Comment by eleijonmarck** [comment]
> In addition, we could do the same for table names, and just backtick all of them, what do you think?

I do think this is the easiest and most understandable solution. Would be curious to see if we can think of the tradeoffs. For now i can't think of any as it is "namings" of tables so they should be backticked

**Comment by DanCech** [comment]
No reason not to quote everything

**Comment by inkel** [comment]
I just updated the code to escape table and column names, and now it is much, much nicer 😸

**Comment by eleijonmarck** [comment]
@inkel and @DanCech tested this on the devdump from the issue to create the backticks for all columns and tables.

It was also successful to be ingested into the MySQL database for the Grafana version that the dump was intended.

Thank you both for this work so far. Let's see what the customer says, but this is a great improvement regardless for the script.

**Pull request merged**
